### ISSUE TITLE
Vue.jsを本番環境に変えると動かない

### ISSUE THREAD

**Issue by takumi1001** [half-blue/A_plus_Tsukuba#17]
# 症状
`vue.js`を本番環境用の`vue.min.js`に変更すると、`/search/`で以下のエラーが発生する。
```
ReferenceError: query is not defined
    at a.eval (eval at ac (vue.min.js:11:104295), <anonymous>:3:87)
    at t._render (vue.min.js:11:44983)
    at a.r (vue.min.js:11:78880)
    at t.get (vue.min.js:11:27634)
    at new t (vue.min.js:11:27547)
    at vue.min.js:11:78894
    at xr.$mount (vue.min.js:11:79112)
    at xr.$mount (vue.min.js:11:106454)
    at init (vue.min.js:11:32902)
    at vue.min.js:11:67187
```
結果、検索バーが表示されない。
# 暫定対応
`vue.js`を利用する。
影響範囲が未知数なため、現状で`vue.min.js`を利用することは良くないかもしれない。
# 将来的にすべきこと
## リファクタリング
`v-model`と`v-on`の併用などはまずいらしくその辺が原因の可能性がある。`/search/`は複雑なイベント機構でうごいており、イベントハンドラ周りが原因の可能性が高い。

**Comment by takumi1001** [comment]
よく見ると`vue.js`でも警告が出ていた
```
[Vue warn]: Property or method "query" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://v2.vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <ChildComponent>
       <Root>
```

**Comment by takumi1001** [comment]
コンポーネント`search.js`を以下のように書き直したところ改善した
```
Vue.component('child-component', {
    data: function () {
        return {
          query: ""
        }
    },
    template: '<input id="search_input" v-model.trim="query" @input="onInput" type="text" class="form-control" placeholder="科目名を入力してください。">',
    methods: {
        onInput: function() {
            this.$emit('childevent', this.query);
        }
    }
});
```
